name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: ${{ secrets.TARGET_SERVER }} # example.com || 8.8.8.8
        SSHKEY: ${{ secrets.PRIVATE_SSH_KEY }} # ----- BEGIN RSA PRIVATE KEY----- ...
        NAME: production
        PORT: 22
        USER: ${{ secrets.REMOTE_USERNAME }} # admin
    - run: ssh production ls --help